[package]
name = "kuchiki"
version = "0.8.1"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "(朽木) HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"
edition = "2018"

[lib]
name = "kuchiki"
doctest = false

[dependencies]
cssparser = "0.27"
matches = "0.1.4"
html5ever = { git = "https://github.com/da-x/html5ever", branch = "patched-0.26" }
selectors = "0.22"

[dev-dependencies]
tempdir = "0.3"
